version: '3.8'

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # image: my_app
    volumes:
      - type: bind
        source: ./app
        target: /app
    networks:
      - uvicorn_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - app
    networks:
      - uvicorn_network

  seed_mongo:
    build:
      context: ./seed
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - uvicorn_network

networks:
  uvicorn_network:
    driver: bridge


